### ISSUE TITLE
Adding keys to all languages

### ISSUE THREAD

**Issue by neomobil** [laravel-enso/localisation#17]
Is there a way to add keys to all languages?

**Comment by aocneanu** [comment]
Yes, just add a key to one language, it will create keys for the other too.

**Comment by neomobil** [comment]
Ok. Just one thing. The add key button is not showing just when you start typing in the search field.
Sorry, I understand now how it works. It adds the key from the search field.

**Comment by aocneanu** [comment]
Can this be closed?

**Comment by neomobil** [comment]
Yes. Thank you!

2018. jan. 30. du. 5:20 ezt írta ("Adrian Ocneanu" <notifications@github.com
