### ISSUE TITLE
Ability to use only the desired languages

### ISSUE THREAD

**Issue by aocneanu** [laravel-enso/localisation#20]
Add is_active to the languages table.

**Comment by dahabit** [comment]
after upgrade localisation to 2.2.0 and run php artisan migrate to add is_active field it saying "Nothing to migrate."

I had to add it manually because i can't run the installation again

**Comment by dahabit** [comment]
I had to add it manually because i can't run the installation again

**Comment by aocneanu** [comment]
The automatic upgrade happens only if you make a git pull to the enso project.

You can use `php artisan enso:update-localisation` command for an existing project.

The reason why we move forward like this is because we want to keep the base project migrations clean.

**Comment by mauthi** [comment]
`php artisan enso:update-localisation`
`There are no commands defined in the "enso" namespace.`

**Comment by aocneanu** [comment]
Sorry. The command  is now in Enso, and should be in the Localisation package.

I will have the time to move over the weekend.
