### ISSUE TITLE
Testresults: Add ability to split enso translations and own translations

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#27]
Add lang

- OK
- New core files are empty - I think this is OK?

Update lang (change shortcode) xx > xy

- Not OK
- /lang/xx.json gets renamed to xy.json
- /lang/enso/xx.json stays xx.json
- /lang/app/xx.json stays xx.json
- fixed in my PR #26

Delete lang

- OK

Update lang file in package and publish changes

- Changes in Core are not published automatically.
- We should add `php artisan vendor:publish --force --tag='localisation-lang-files'` to `php artisan vendor:publish --force --tag='enso-assets'` (but publish enso lang files only, not core lang files)
- added the change to my PR #26
- **Needed Change: Add `php artisan localisation:merge` to composer `post-update-cmd`**

Merge translations

- Message was wrong `Language files merged ("")!` because of `protected $signature = 'localisation:merge {--L|locale="" : Language key to merge (default: all)}';` sends `""` as string.
- Changed signature to `protected $signature = 'localisation:merge {--L|locale= : Language key to merge (default: all)}';`
- added the change to my PR #26

Add translation key (core and app)

- OK

Remove translation key (core and app)

- OK

Change translation (core and app)

- OK

Test collectMissingKeys on/off (frontend / core = true, core = false)

- OK

Feature request: can we store files with line breaks in enso and app dir because it makes it easery to compare files and merge PRs - in the merged file it's ok to store them without line breaks.
- added the change to my PR #26

**Question: Should the state of Key collector get stored locally? At the moment its Off after every reload?**

**Comment by mauthi** [comment]
Also needed: Update of documentation

**Comment by aocneanu** [comment]
>New core files are empty - I think this is OK?

By empty you mean they have all the keys and the values are `null`?

**Comment by aocneanu** [comment]
>Question: Should the state of Key collector get stored locally? At the moment its Off after every reload?
Nope. We want to use this flag with care.

**Comment by aocneanu** [comment]
>We should enso lang files to php artisan vendor:publish --force --tag='enso-assets' 

Correct.

>Needed Change: Add php artisan localisation:merge to composer post-update-cmd

Correct.

Do you want to make this changes or I will?

Thanks.

**Comment by mauthi** [comment]
no, I mean they are empty without any key

**Comment by mauthi** [comment]
> Do you want to make this changes or I will?

would be nice if you can make this change

**Comment by aocneanu** [comment]
Strange. When I create a new language i get jsons with the keys and null values.

I will make the changes tomorrow, and test again.

**Comment by mauthi** [comment]
ok, if you are not able to reproduce it will test it again.

Btw. whats the source for the keys for new languages? The keys of loaded language?

**Comment by aocneanu** [comment]
[the first extra()](https://github.com/laravel-enso/Localisation/blob/master/src/app/Handlers/Json/Storer.php)

**Comment by aocneanu** [comment]
Added both.

Right now, on every automatic hit on `addKey` a merge (all) command executes. This is not optimal. On a page with 20 new labels, and having 20 languages, the app will make 20 requests and 20*20 merges.

I think that the best solution is to cancel the logic that does the auto merge, and do the merge manually, once all the labels were gathered.

**Comment by mauthi** [comment]
> I think that the best solution is to cancel the logic that does the auto merge, and do the merge manually, once all the labels were gathered.

We can add a "merge" button to FE below "key collector switch"?

**Comment by aocneanu** [comment]
I think that it would fit better somewhere in the localisation structure.. maybe on the EditTexts page.

**Comment by mauthi** [comment]
also ok
