### ISSUE TITLE
Missing translations on user profile

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#28]
As you can see on screenshot the translations on user profile are missing:
(screenshots are from https://www.laravel-enso.com/administration/users/1)

![screenshot 2018-03-23 19 18 49](https://user-images.githubusercontent.com/7204559/37846879-51f5cbdc-2ecf-11e8-8385-a46f286e29db.png)
![screenshot 2018-03-23 19 18 38](https://user-images.githubusercontent.com/7204559/37846880-52120414-2ecf-11e8-8f01-b52d73946da0.png)

**Comment by aocneanu** [comment]
Indeed, still uses the mapGetter. FIxing it now.
