### ISSUE TITLE
Collect missing core keys

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#29]
I will checkout a fresh enso and click through app

**Comment by aocneanu** [comment]
Now we need a tutorial with the steps for updating the core localisation. After we will kindly ask our contributors to fill the blanks

**Comment by mauthi** [comment]
Do you have an idea whats the easies way to update them?

Here is my suggestion:

1) composer update to get current /lang/enso/ files with new keys
2) translate keys with UI
3) copy content of /lang/enso/xx.json
4) Go to https://github.com/laravel-enso/Localisation/tree/master/src/resources/lang/enso
5) select your language file
6) click on pencil to edit file
7) paste your translations
8) propose file change

**Comment by aocneanu** [comment]
I think that probably we need to modify the auto merging and add a button for this.

Then:

Step 1 clone a fresh project

Step 2.5 click the merge button

The rest sounds fine

**Comment by mauthi** [comment]
Can you do this?

> Step 1 clone a fresh project

Not necessary - because the keys are already collected, so they can use their up2date project to translate the keys?

**Comment by aocneanu** [comment]
>Not necessary - because the keys are already collected, so they can use their up2date project to translate the keys?

Just look at how many issues users open because they fail to update the project and try to extrapolate. Cloning is safer.

And yes, I will add the button.

**Comment by mauthi** [comment]
> Just look at how many issues users open because they fail to update the project and try to extrapolate. Cloning is safer.

You are right!

**Comment by mauthi** [comment]
Quick idea: Should we create an issue for every existing language and leave it open?

**Comment by aocneanu** [comment]
Yes!

But first let's sort out all the problems with localisation, like the login pages and so on.

**Comment by mauthi** [comment]
for sure

**Comment by aocneanu** [comment]
I think that we are ready for this step.

**Comment by mauthi** [comment]
sorry I don’t have time this week and I’m not sure anymore what this step should be :)
Only create one issue per language?

**Comment by gandesc** [comment]
No worries, there's no rush :grinning: 

The steps for adding the missing translations are also in the [localization docs](https://github.com/laravel-enso/Localisation#contributing-translations-for-an-existing-language)

**Comment by aocneanu** [comment]
I think that we need a new issue for each language, with tagging of the original contributor.
