### ISSUE TITLE
Language of login page

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#35]
Do you know how the language of login page is selected?
It should be taken from browser language, but for me it's english instead of german.

Same for mails (e.g. password forgotten)

**Comment by aocneanu** [comment]
Yeah, it's in the config('app.locale') / config('app.fallback_locale').

For emails we should use the user's preferred lang.

**Comment by mauthi** [comment]
config/app.php: `'locale' => 'de',` 

But login screen is still in english:
![screenshot 2018-03-26 20 04 58](https://user-images.githubusercontent.com/7204559/37924046-02eb83a6-3131-11e8-992a-d6bf23afa3ca.png)
