### ISSUE TITLE
Datepicker in Form: Select Date not translated

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#36]
This is  a bug.

### Description
The `Select Date` in datepicker is not translated, even if we add it as key

### Steps to Reproduce
Create a form with datepicker

### Expected behavior
`Select Date` should be replaced with translated value

### Actual behavior
`Select Date` is not replaced with translated value

**Comment by aocneanu** [comment]
It was a problem with the placeholders in vue-form, they were not translated. It's fixed in laravel-enso/formbuilder@106e70c.

Don't forget to add the placeholder in the form template, in the field's meta section.

Sepparately, I added localisation for the datepicker component.

From now on, whenever we add a new language we will have to update this file as well:

https://github.com/laravel-enso/FormBuilder/blob/106e70c7f7d09249c8063f7712403698ec529b55/src/resources/assets/js/components/enso/vueforms/flatpickrLocale.js

**Comment by mauthi** [comment]
The datepicker keys are not collected - should this work?

And at the moment we get collected an empty key - we should add something like `if key == '' don't collect`

(if needed I will open an issue for each of the 2 parts)

**Comment by aocneanu** [comment]
what do you mean by "datepicker keys"?

**Comment by mauthi** [comment]
March
Mon
Tue
…

Btw. can we set the begin of week (mon instead of sunday)?
And is there a possibility to change the theme from outside without overwriting the component?
(I can create an own ticket for this within vue components if needed)

**Comment by aocneanu** [comment]
Datepicker is a wrapper for the Flatpickr library. This library has its own localisation. With this https://github.com/laravel-enso/FormBuilder/commit/106e70c7f7d09249c8063f7712403698ec529b55 I integrated the Flatpickr's native localisation with enso. So all the "keys" are now translated.

For the themes, we were also condering an approach, but please open a new ticket. Note that right now datepicker is a part of formbuilder (package). In the future we will created a dedicated npm / github package for this.

**Comment by mauthi** [comment]
> Datepicker is a wrapper for the Flatpickr library. This library has its own localisation. With this laravel-enso/FormBuilder@106e70c I integrated the Flatpickr's native localisation with enso. So all the "keys" are now translated.

Should this work already? Or do I have to set/change anything in my forms for this?

**Comment by aocneanu** [comment]
- Composer update
- add the placeholder to the form template in the date column’s meta

Play

**Comment by mauthi** [comment]
Sorry, you got me wrong: The select date placeholder is already working like described.
I’m talking of the other strings like month names, day names - they are in english

**Comment by aocneanu** [comment]
![image](https://user-images.githubusercontent.com/16073274/38073347-501c21c2-3333-11e8-8906-9743df2cd76f.png)


![image](https://user-images.githubusercontent.com/16073274/38073354-5923bf78-3333-11e8-8855-102b5a40870d.png)

**Comment by aocneanu** [comment]
what does your dev tools show for the datepicker? (locale)

![image](https://user-images.githubusercontent.com/16073274/38073399-7dc5786c-3333-11e8-8856-a85e0803713d.png)

**Comment by mauthi** [comment]
Its "en"
![screenshot 2018-03-29 08 33 43](https://user-images.githubusercontent.com/7204559/38073589-06465c7c-332c-11e8-94f5-516707d447cf.png)

Do I have to set the locale anywhere? Or where do you set it?

**Comment by aocneanu** [comment]
from here

![image](https://user-images.githubusercontent.com/16073274/38074522-aa1c9284-3337-11e8-8bfa-4db288571318.png)

**Comment by mauthi** [comment]
![screenshot 2018-03-29 09 02 03](https://user-images.githubusercontent.com/7204559/38074686-dfb825f0-332f-11e8-9b8f-7148dac233ba.png)

**Comment by aocneanu** [comment]
Ah maybe you're not using the VueFormSS wrapper?

If not you should always pass the user's locale to the vue-form component.

**Comment by mauthi** [comment]
That was the mistake - just changed it to VueFormSS
