### ISSUE TITLE
Document title not translated after reload

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#37]
This is  a bug.

### Description
After reload of browser window the document title is not translated

### Steps to Reproduce
Open enso and reload page

### Expected behavior
![screenshot 2018-03-26 22 30 02](https://user-images.githubusercontent.com/7204559/37931261-5ade4422-3145-11e8-9ce3-a806980f4a4f.png)

### Actual behavior
![screenshot 2018-03-26 22 29 53](https://user-images.githubusercontent.com/7204559/37931271-5df95bce-3145-11e8-9335-a144bffb5958.png)

**Comment by aocneanu** [comment]
Yeah, that happens because on page reload the document title is displayed before the app initialises. It needs to be that way in order to have doc.title in auth pages too.

Anyway when you click the next link, the localisation works as expected.

I will think of something..
