### ISSUE TITLE
Errors on login page (in 2.5.5)

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#38]
This is  a bug | feature request

### Prerequisites
* [ x ] Are you running the latest version?
* [ x ] Are you reporting to the correct repository?
* [ x ] Did you check the documentation?
* [ x ] Did you perform a cursory search?

### Description
2 Errors on login page after update
- placeholder wrong
- console errors

### Steps to Reproduce
Update to 2.5.5. and go to login page

### Expected behavior
-

### Actual behavior
see Screenshots

![screenshot 2018-03-28 18 09 16](https://user-images.githubusercontent.com/7204559/38041952-5c90cc6c-32b3-11e8-8dd8-ef3f04251567.png)
![screenshot 2018-03-28 18 09 09](https://user-images.githubusercontent.com/7204559/38041954-5cb7d21c-32b3-11e8-8d0d-8a93b33e11d7.png)

**Comment by aocneanu** [comment]
'Remember me' key may be missing. Update to the latest core.
