### ISSUE TITLE
Toastr title not translated on login screen

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#40]
This is  a bug.

### Description
Toastr title not translated on login screen

### Steps to Reproduce
Go to login screen
Enter invalid data
Click button

### Expected behavior
Title of error badge should be translated

### Actual behavior
Title of error badge is not translated

![screenshot 2018-03-29 08 14 46](https://user-images.githubusercontent.com/7204559/38073412-314396a2-332b-11e8-821d-f373670db63c.png)
![screenshot 2018-03-29 08 11 05](https://user-images.githubusercontent.com/7204559/38073413-315cfef8-332b-11e8-8ac0-905b67f5d088.png)

**Comment by aocneanu** [comment]
They translate on my dev version. Are you sure that you have everything updated to the last versions?

![image](https://user-images.githubusercontent.com/16073274/38073714-de3b7e52-3334-11e8-8d28-5148339c505f.png)


![image](https://user-images.githubusercontent.com/16073274/38073733-e955871a-3334-11e8-89e1-d3f2df854a00.png)

**Comment by mauthi** [comment]
If I'm logged in the title is translated - but not on **login and passwort reset page**.

**Comment by aocneanu** [comment]
Please add the missing keys here

https://github.com/laravel-enso/Core/blob/master/src/app/Http/Controllers/GuestController.php

**Comment by mauthi** [comment]
thx, works!

**Comment by mauthi** [comment]
I leave it open because I think you will add it to core as well.

**Comment by aocneanu** [comment]
>Please add the missing keys here

By this I was asking you to do this contribution ;)

**Comment by mauthi** [comment]
done
