### ISSUE TITLE
Translate time info in notifications

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#43]
This is  a feature request.

### Description
See screenshot

At the moment the time info in notifications is not translated.
Be aware that we have different possibilities here:
- lass than a minute
- xx minutes
- ...

### Steps to Reproduce
Login
Request a new export
run `php artisan queue:work`

### Expected behavior
Time info should be translated

### Actual behavior
Time info is in EN

**Comment by aocneanu** [comment]
closed with laravel-enso/core@7ac6b86
