### ISSUE TITLE
can_store_language expects deleted files

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/localisation#49]
This is  a **bug**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Json\Storer expects `app/<lang>.json` & `enso/<lang>.json` files to exist.
However, these files, even if present, are being automatically deleted since 544b399cc60b4b39e94b7d4cb85e9513e6d14f01

### Steps to Reproduce
1. run localisation's `can_store_language` test

### Expected behavior

tests to pass

### Actual behavior

expects files to be present that are getting deleted in the test cleanup, reproducible across windows (10) & Linux (CentOS)

**Comment by aocneanu** [comment]
![image](https://user-images.githubusercontent.com/16073274/47664716-58774400-dba8-11e8-83a8-cd1a80c90276.png)

**Comment by aocneanu** [comment]
comment in `config/telescope.php` the `Watchers\QueryWatcher`

**Comment by jlsjonas** [comment]
That was the issue indeed; However I feel that's just _hiding_ a bug, as it should just limit query parallelisation.

disabled the watcher for phpunit only for now ( `<env name="TELESCOPE_QUERY_WATCHER" value="false"/>` )
