### ISSUE TITLE
Language not set in Laravel session?

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/localisation#50]
This is  a **bug | feature request**. (I consider it a bug as it's implied to be using Laravel's methods)

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

It seems that using `__()` in php doesn't cause the translation to appear; but instead the original (english) key.

I've checked the docs and _the new system_ does match with Laravel's expectancy, so it should just be the `setLocale()` that's missing

### Steps to Reproduce
1. Try to translate a string (using `__(...)` from within php (for example in a Form controller)
2. Ensure your language is different from English AND the _key_ used above is defined
3. Note the english (key) version is kept.

### Expected behavior

Translated text to appear

### Actual behavior

orginal (key) shown instead

**Comment by aocneanu** [comment]
Are you using the correct middleware on that route?

**Comment by jlsjonas** [comment]
... 🤦‍♂️ 

Thanks!

edit: for the next guy, add `->middleware(['core'])` to (api/other) routes that need access to localisation
(maybe to be considered for the StructureManager template?)
