### ISSUE TITLE
Support parameters in keys

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/localisation#51]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

Expanding the FE translation (`__`) api to also support parameters (as [documented by Laravel](https://laravel.com/docs/5.7/localization#replacing-parameters-in-translation-strings))

### Use Case example
Several sentences are formed differently in different languages, having simple parameters in the string allows the translator to choose the order without requiring weird programming logic

ex.: when describing "something happened at <date>", in German the date usually comes first.
There are more useful uses too though; like having a status mid-sentence (without requiring 2 _weird_ keys to make up the sentence)

**Comment by aocneanu** [comment]
I want this too by won't be able to work on it too soon.

A PR would be appreciated.

**Comment by jlsjonas** [comment]
FYI: had other priorities popping up but I should be able to provide a PR for this _soonish_ (with a bit of luck this week; otherwise more towards 2nd week of december)

**Comment by jlsjonas** [comment]
It turns out implementing this was simpler than expected.

PR coming up (in Core, as changes were in the `__` mixin & localisation store only; which resides there)

Notables:
- Key collection code was moved to the store to improve compatibility (`__` can be called from within the store too, previously this didn't trigger the collector) & allow collecting of parameterized keys (_cleanly_)
- It does also support uppercasing according to the parameter (full uppercase & first letter uppercased)

- _We_ should probably consider moving the missing key logic (tracking array & request) outside of the main store to reduce code smell (the store is being imported into the localisation module as that sadly enough was the cleanest solution without moving `addMissingKey` out of the localisation store; it works; I haven't discovered any issues doing it this way; but it's most likely wasting some resources)

Thoughts on/possibilities for `addMissingKey`:
- Leave as is (should be ok as it's a route only used on local environments, basically as a development aid; long-term effects unknown)
- Move to a separate store (is it worth creating a store for an `axios.patch` & storing an array?
- Make the patch call directly from the getter; store the _pending_ keys in a `window` or `document`-level array?

**Comment by aocneanu** [comment]
Sorry for the delay but I'm abroad and I have limited time near the computer.

>Key collection code was moved to the store to improve compatibility (__ can be called from within the store too, previously this didn't trigger the collector) & allow collecting of parameterized keys (cleanly)

From the store point of view `__` is a getter. From the app point of view `__` is a global helper for translation. Before having the key collection logic the global helper's role was just avoiding having to use mapGetters in every component.

Moving the key collection logic to the store, as a general idea does not increase any "compatibility", you already have access to `this.__` from every component and don't need to map the getter.

The current implementation for the key collector was not the cleanest architectural choice but its utility combined with the fact that is usable only in dev mode made it worth it.

I'll comment further on the PR.

**Comment by jlsjonas** [comment]
>Sorry for the delay but I'm abroad and I have limited time near the computer.

No problem

> The current implementation for the key collector was not the cleanest architectural choice but its utility combined with the fact that is usable only in dev mode made it worth it.

I understand, hence why it remained intact (but moved to the store as you don't have the middleware available from within the store)

> and don't need to map the getter.

No indeed, but you had to manually add the keys instead of them being collected with anything using `this.__`; with the move this is no longer the case.

**Comment by aocneanu** [comment]
>No indeed, but you had to manually add the keys instead of them being collected with anything using this.__; with the move this is no longer the case.

What do you mean?

**Comment by jlsjonas** [comment]
![image](https://user-images.githubusercontent.com/932193/49793724-22e08180-fd36-11e8-9fd2-4d9fd9836b41.png)


That code is located in the store (as it affects the store & is used globally in different ways)
The mixin doesn't apply here; and thus it's logic had to be moved to the store itself for it to work as expected (more cases are following where we require a similar approach)

edit: note that "incorrect credentials" here only applies to a temporary (non-Enso) _authentication_ required in certain cases; it's unrelated to the actual session's login user

**Comment by aocneanu** [comment]
Now I think I understand your problem. We can extract the helper function in a file and import it in the mixin file, or wherever we need it.

**Comment by jlsjonas** [comment]
Sounds like a reasonable alternative.
Sorry for the late reply btw, I've been coping with illness.
I'll make the requested changes _soon_ (will be for next week though as I have to catch up & holidays coming up starting wednesday ;) )

**Comment by aocneanu** [comment]
Where are we on this?

**Comment by jlsjonas** [comment]
Only got back from holiday yesterday, will be done after completing our backlog (~~hopefully tomorrow~~ now)

**Comment by jlsjonas** [comment]
Updated, see https://github.com/laravel-enso/Core/pull/87
