### ISSUE TITLE
Support filtering on translation values in editTexts

### ISSUE THREAD

**Issue by jlsjonas** [laravel-enso/localisation#53]
This is  a **feature request**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description

It would be really useful if the _editTexts_ search feature allowed searching on value alongside key

### Use Case
Noticing a bad translation; requiring to look up in the code where it's generated to (in most cases it's the more _secluded_ items that have bad translations, so just toggling language isn't a solution in those cases + they're often reported _in the field_ (and they just have a globally set language + can't be asked for that info)

### Remarks

I noticed key-based filtering is embedded quite deeply (likely due to the missing-key logic; which is a great feature too!) if you have an implementation method idea that wouldn't cause a big hit on performance I'm definitely willing to PR this.

**Comment by aocneanu** [comment]
If you switch the language to English don't should see the key instead of the translation? Because if you do then you can filter by that key.

**Comment by jlsjonas** [comment]
Not if we receive a screenshot from a user of a dialog that only appears in certain cases (for example)

**Comment by aocneanu** [comment]
>It would be really useful

This is and edge case, more like *it would be extremely rarely useful*.

When this happen the user can still switch to en and determine the key. If he does not know how to do that and instead sends you a printscreen you can easily search by the translation in the JSON file and get the key. 

But if you want to make a PR for this to implement it in a cleam manner be my guest.

**Comment by jlsjonas** [comment]
>you can easily search by the translation in the JSON file and get the key.

Those responsible for translations don't have direct access (nor proper knowledge to handle) such files though.
I'll see how cleanly I can implement it and PR if so.

Given the current structure the _best_ implementation method would likely be to filter by value only if no results are returned (to reduce _regular_ load)

**Comment by aocneanu** [comment]
>Given the current structure the best implementation method would likely be to filter by value only if no results are returned (to reduce regular load)

I think that the best approach would be to filter by both (key OR value) at all times. Are you experiencing performance problems with the current filter?

**Comment by jlsjonas** [comment]
>Are you experiencing performance problems with the current filter?

No I'm not, but given the added complexity the double-filter would introduce I expect a (slightly?) noticeable slowdown for lower-end devices; This shouldn't be a big issue for the translation page itself though (less likely to be a low-end device)

I'll add it _at all times_
