### ISSUE TITLE
Localisation of login/password reset

### ISSUE THREAD

**Issue by mauthi** [laravel-enso/localisation#58]
This is  a **question**.

### Prerequisites
* [x] Are you running the latest version?
* [x] Are you reporting to the correct repository?
* [x] Did you check the documentation?
* [x] Did you perform a cursory search?

### Description
I have 2 questions
- How can I set the language of login screen (I changed it in local and vendor preferences.json but this did not change anything - I also deleted preferences table and app cache first) (btw: Setting default theme is also not working)
- How can I set the translations for toastr messages on password reset screen (they are set in the json file and in lang/de/passwords - but both keys are not used and I get an empty toastr)

**Comment by aocneanu** [comment]
I change the architecture of the FE key collection / BE patching.

Run composer update, compile and play with it.

@gandesc we will need docs update on this

**Comment by aocneanu** [comment]
>How can I set the language of login screen ...

If you want a default language for the Auth views you should set that language in Laravel's `app.php` config file, in the `locale` key.

Once a user sets (changes) his locale in the app the value will be saved in localStorage and on the next visit to the Auth pages will be sent in the `/meta` request

![image](https://user-images.githubusercontent.com/16073274/52321429-632e4a00-29dd-11e9-94ea-21954bcc778f.png)

>How can I set the translations for toastr messages on password reset screen ...

Look in `Core\....\GuestState` and see what translations are missing from the `i18n` method.

**Comment by mauthi** [comment]
Thx - works!
