### ISSUE TITLE
Error exception when trying to publish assets

### ISSUE THREAD

**Issue by alin78hai** [laravel-enso/localisation#6]
There is an error when trying to publish assets from enso-core.

Here is an screenshot and a log of the error:

![170620103037](https://user-images.githubusercontent.com/13088749/27321634-960a8f2a-55a3-11e7-979a-6ff4e39aea4e.png)

[2017-06-20 10:20:36] local.ERROR: ErrorException: include(S:\Code\Laravel\enso-test\resources\lang/en/en\auth.php): failed to open stream: No such file or directory in S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Classes\LangFilesManager.php:64
Stack trace:
#0 S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Classes\LangFilesManager.php(64): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'include(S:\\Code...', 'S:\\Code\\Laravel...', 64, Array)
#1 S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Classes\LangFilesManager.php(64): include()
#2 S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Classes\LangFilesManager.php(55): LaravelEnso\Localisation\app\Classes\LangFilesManager->getFileContent('en\\auth.php')
#3 S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Classes\LangFilesManager.php(47): LaravelEnso\Localisation\app\Classes\LangFilesManager->getTranslationsFromFile('en\\auth.php')
#4 S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Classes\LangFilesManager.php(17): LaravelEnso\Localisation\app\Classes\LangFilesManager->getTranslations()
#5 S:\Code\Laravel\enso-test\vendor\laravel-enso\localisation\src\app\Commands\Generate.php(24): LaravelEnso\Localisation\app\Classes\LangFilesManager->__construct('en')
#6 [internal function]: LaravelEnso\Localisation\app\Commands\Generate->__construct()
#7 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(762): ReflectionClass->newInstanceArgs(Array)
#8 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(608): Illuminate\Container\Container->build('LaravelEnso\\Loc...')
#9 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Container\Container.php(575): Illuminate\Container\Container->resolve('LaravelEnso\\Loc...')
#10 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(728): Illuminate\Container\Container->make('LaravelEnso\\Loc...')
#11 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Console\Application.php(192): Illuminate\Foundation\Application->make('LaravelEnso\\Loc...')
#12 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Console\Application.php(206): Illuminate\Console\Application->resolve('LaravelEnso\\Loc...')
#13 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Support\ServiceProvider.php(232): Illuminate\Console\Application->resolveCommands(Array)
#14 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Console\Application.php(111): Illuminate\Support\ServiceProvider->Illuminate\Support\{closure}(Object(Illuminate\Console\Application))
#15 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Console\Application.php(58): Illuminate\Console\Application->bootstrap()
#16 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(284): Illuminate\Console\Application->__construct(Object(Illuminate\Foundation\Application), Object(Illuminate\Events\Dispatcher), '5.4.27')
#17 S:\Code\Laravel\enso-test\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(122): Illuminate\Foundation\Console\Kernel->getArtisan()
#18 S:\Code\Laravel\enso-test\artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 {main} 

It seems that problem lies in \Classes\LangFileManager.php where the directory separator is hard-coded to '\'. When i change it to the PHP constant DIRECTORY_SEPARATOR, the error is resolved.

**Comment by aocneanu** [comment]
Hello,

We are currently in a process of upgrading all the Enso packages to a more friendly and less technical structure. 

I expect that everything will be wrapped up by the end of this week, including the review and sync of all the readme files (at least the installation steps)

A demo wil be available at www.laravel-enso.com.

Until then, i kindly ask you to be patient with us:)

**Comment by alin78hai** [comment]
Ok, nici o problema. Spor la munca

**Comment by aocneanu** [comment]
Salut,

Cu ceva intarziere dar pana la urma am reusit sa punem sus ceva coerent. Am corectat si problema pe care ai intalnit-o pe windows.

Daca ai timp si chef iti recomand sa incepi de aici

https://github.com/laravel-enso/Enso <https://github.com/laravel-enso/Enso>

Seara buna :)

Adrian Ocneanu
0722 44 33 77
